### ISSUE TITLE
Paste bug

### ISSUE THREAD

**Issue by AbleTheAbove** [curlpipe/ox#11]
**Describe the bug**
Pasting into Ox with LXTerminal creates mangled data
Edit: Deepin Terminal as well
**To Reproduce**
Steps to reproduce the behaviour:
1. run `ox example.txt`
2. paste in a string/sentence
3. see mangled version of string

**Expected behavior**
Paste in data without it becoming mangled

**Desktop (please complete the following information):**
 - OS: Debian Linux

**Comment by AbleTheAbove** [comment]
RE: I think it has something to do with how characters are pasted/inserted 

I tried pasting a fairly large bit of text and watched the cursor spasm about the terminal.

**Comment by curlpipe** [comment]
Finally fixed, yay!
