### ISSUE TITLE
Outputing editors state for discord rpc

### ISSUE THREAD

**Issue by d3r1n** [curlpipe/ox#114]
**Hello!**
I'm going to make a **Discord RPC** for *ox* but I can't get any information about editors state (like, filename, line number, total lines, visual - editing mode etc.). Is there any way for me to get those information from ox?

**Comment by curlpipe** [comment]
Implemented in 0.6.7

See [documentation](https://github.com/curlpipe/ox/wiki/Plugins#discord-rpc) for installation and usage instructions
