### ISSUE TITLE
YAML syntax highlighting support

### ISSUE THREAD

**Issue by lanceschi** [curlpipe/ox#115]
Is there a way to tweak the default [ron configuration file][conf-file-url] in order to support [yaml][yaml-site-url] syntax highlighting?

Thanks :100: for the awesome editor!

[conf-file-url]: https://github.com/curlpipe/ox/blob/master/config/ox.ron
[yaml-site-url]: https://yaml.org/

**Comment by iamgabrielsoft** [comment]
Yes it's possible

**Comment by curlpipe** [comment]
Yaml is now included as standard in the new version (0.3.0)
