### ISSUE TITLE
Smart rendering

### ISSUE THREAD

**Issue by curlpipe** [curlpipe/ox#12]
**Is your feature request related to a problem? Please describe.**
Ox still uses too much CPU despite the improvements implemented in 0.1.1. It also flickers in the TTY whenever the keyboard is interacted with.

**Describe the solution you'd like**
I would like Ox to use far less CPU by rendering the necessary lines e.g. only the status line and actual cursor position when using the relevant keys.

**Comment by curlpipe** [comment]
Fixed the flickering in the TTY in 68ed60c

**Comment by ChayimFriedman2** [comment]
GPU-based rendering?

**Comment by curlpipe** [comment]
@ChayimFriedman2 Correct me if I'm wrong but I believe that is down to the terminal emulator.

**Comment by ChayimFriedman2** [comment]
You're right.
