### ISSUE TITLE
To Tab, or not to Tab? 

### ISSUE THREAD

**Issue by d4140n-4h3-1** [curlpipe/ox#122]
As someone who uses Nano, the only issue I have with is how Ox deals with tabs. Some of us are not used to reopening files to find spaces, plus it somewhat wastes time to backspacing if we need to correct our formatting.

**Comment by curlpipe** [comment]
The newest version of ox (0.3.0 and up) should hopefully deal with tabs much better
Even if spaces are used, they are treated as one character would be, and can be deleted and moved over with the cursor with just one click of a button
