### ISSUE TITLE
Keep cursor's position

### ISSUE THREAD

**Issue by severny-polus** [curlpipe/ox#124]
Cursor is not keeping its position when you swap the line with Up/Down keys. When the line is shorter, it should appear at the end of line. But when you swap to line of the same length or longer through the lines that are shorter, the cursor should take its original position. In particular, when you sequentially press Down, Up, the cursor should take the same position it was before, even if the next line is shorter.

**Comment by curlpipe** [comment]
This was implemented in version 0.4.6
