### ISSUE TITLE
ox faield to start

### ISSUE THREAD

**Issue by subham008** [curlpipe/ox#126]
runtime error 

thread 'main' panicked at src\main.rs:65:5:
Err(Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I  had installed it using manual command i.e -  cargo install <ox git link> 
OS - windows 11

**Comment by curlpipe** [comment]
I think this may be down to the file you're wanting to open not existing?

There's a new version, but this doesn't handle non existent files very well (it will just exit)

I'll look to change this in the next release

**Comment by curlpipe** [comment]
New change in 0.3.1:

If you pass a file that doesn't exist, Ox will now create it as a new file instead, and then put that on disk when you save

Hopefully this should be resolved
