### ISSUE TITLE
Just a thought:  tree editing

### ISSUE THREAD

**Issue by demosthenez** [curlpipe/ox#127]
**Is your feature request related to a problem? Please describe.**
I'm sorry but I'm not sure if I could answer this clearly.  I'll try.  There can be issues with navigating code where tree-smart navigation might help, I suppose.

**Describe the solution you'd like**
Just seems like a cool idea/feature that doesn't show up many places.  Somehow integrated with a micro style editor seems like a cool idea.  Maybe modes would be required, though, and this might move away from micro/nano simplicty toward vim.

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.](https://github.com/Nimaoth/Absytree) That is a project working toward tree-editor ends.

**Comment by curlpipe** [comment]
That is certainly an interesting approach to navigating files.
It would be quite a substantial feature I feel, especially as I would likely have to include a full-blown parser for multiple different languages into the editor.

I'll consider it, but if worked on, will likely not be implemented for a while as there are some basics that still need implementing first.

Either way, thanks for your suggestion!

**Comment by curlpipe** [comment]
Nev (was Abystree) is a great editor, and it covers the realm of tree editing nicely. For now, I'll close this issue as Ox likely won't go in the same direction.

Either way, thank you for your suggestion as it has given me plenty of food for thought.
