### ISSUE TITLE
Add support for latex (and add comments for nushell)

### ISSUE THREAD

**Issue by kurokirasama** [curlpipe/ox#128]
**Is your feature request related to a problem? Please describe.**

Is it possible to add syntax highlighting for nushell?
Is it possible to add it manually?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by curlpipe** [comment]
There's currently no way in versions 0.3.0 and up to add your own syntax highlighting

This is something that I'm looking to add at some point in the future

However, I'll make it such that nushell files are highlighted in the next release :+1:

**Comment by kurokirasama** [comment]
super!! Thank!!

Regards.

**Comment by curlpipe** [comment]
implemented in version 0.3.4 (just released)

**Comment by kurokirasama** [comment]
thanks! for the update, a small problem is that comments aren't recognized (with `#`)

On another hand, can you add tex (latex) files, please?

**Comment by curlpipe** [comment]
Noted! I will look to add latex and comments to nushell ready for the next release

**Comment by curlpipe** [comment]
Latex and nushell comments added in 0.4.1
