### ISSUE TITLE
0.5.0 tagged on wrong commit

### ISSUE THREAD

**Issue by chenrui333** [curlpipe/ox#139]
👋 looks like 0.5.0 tagged on a wrong commit, so that the archive tarball does not have files in kaolinite folder.

relates to https://github.com/Homebrew/homebrew-core/pull/189531

**Comment by curlpipe** [comment]
Good catch. I'll issue 0.5.1 with the corrections.
Hopefully that mitigates the issue.

**Comment by chenrui333** [comment]
Thanks @curlpipe!
