### ISSUE TITLE
show Key Binding Cheat Sheet instead of default help

### ISSUE THREAD

**Issue by kurokirasama** [curlpipe/ox#147]
**Is your feature request related to a problem? Please describe.**
is there a way to show the Key Binding Cheat Sheet instead of default help with `ctrl + h`?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by curlpipe** [comment]
I'm not quite sure what you mean
Do you mean adding a key binding `ctrl h` in the default configuration to open the help message (shown below in green)?

![image](https://github.com/user-attachments/assets/06f65ab4-0b12-4b71-91ef-384f24a1f7da)

If so, you can use the following code in your configuration file (in the event mapping part) to toggle the help message when pressing ctrl_h

```lua
    ["ctrl_h"] = function()
        if editor.help_visible then
            editor:hide_help_message()
        else
            editor:show_help_message()
        end
    end,
```

I can add this into the default config in future, as it makes sense

**Comment by kurokirasama** [comment]
Hey, 

the config file use to have this (I added a few more):
```lua
Key Binding Cheat Sheet
{highlight_start}
Ctrl + N:   New         
Ctrl + O:   Open        
Ctrl + Q:   Quit        
Ctrl + S:   Save        
Ctrl + A:   Save all    
Ctrl + Z:   Undo        
Ctrl + Y:   Redo        
Ctrl + F:   Find        
Ctrl + R:   Replace     
Ctrl + D:   Delete Line 
Ctrl + L:   Clear file
Ctrl + J:   Join the current line with the next one
Ctrl + G:   Go to line
Ctrl + K:   Comment line
Ctrl + B:   Compile md via Pandoc
Alt + D:    Duplicate current line 
Alt + S:    Save all
Alt + K:    Command line 
Alt + W:    Remove previous word
Alt + L:    Toggle line numbers
Alt + O:    Open current file in default system app
Shift + up: Move line up 
Shift + dn: Move line down 
Shift + ->: Next Tab    
Shift + <-: Previous Tab
{highlight_end}
]]
```

I have that ctrl_h function, but it only shows the default, not what I added...

**Comment by curlpipe** [comment]
I think I understand. The above part of the configuration file is the "greeting message" which shows when you start the editor. You want the help message that is shown to match the greeting message you have there in the configuration file.

I might change the greeting message to be simpler but have the help message will be more detailed and can be changed in the config file.

**Comment by curlpipe** [comment]
So this should be clearer in release 0.6.2

There is now a `help_message` table in the configuration file that will allow you to modify the contents of the built-in help message.

See the default configuration file [here](https://github.com/curlpipe/ox/blob/master/config/.oxrc) for how I've implemented it in default Ox.

Go [here](URL) if you would like to see the documentation.

Note that the `show_help_message()` and `hide_help_message()` and `editor.help_visible` are all now depreciated.

I've added the `ctrl + h` command by default into Ox, and the command looks like this (using the new API)

```lua
    ["ctrl_h"] = function()
        help_message.enabled = not help_message.enabled
    end,
```

:warning: The old command to toggle the help message is now depreciated and it won't work in later versions of Ox, so be sure to use the above one instead.

As for the help message you'd want (based on the key bindings you provided above) try adding this to your configuration file:

```lua
-- Configure Help Message --
help_message.enabled = false
help_message.format = [[
Key Binding Cheat Sheet
{highlight_start}
Ctrl + N:   New         
Ctrl + O:   Open        
Ctrl + Q:   Quit        
Ctrl + S:   Save        
Ctrl + A:   Save all    
Ctrl + Z:   Undo        
Ctrl + Y:   Redo        
Ctrl + F:   Find        
Ctrl + R:   Replace     
Ctrl + D:   Delete Line 
Ctrl + L:   Clear file
Ctrl + J:   Join the current line with the next one
Ctrl + G:   Go to line
Ctrl + K:   Comment line
Ctrl + B:   Compile md via Pandoc
Alt + D:    Duplicate current line 
Alt + S:    Save all
Alt + K:    Command line 
Alt + W:    Remove previous word
Alt + L:    Toggle line numbers
Alt + O:    Open current file in default system app
Shift + up: Move line up 
Shift + dn: Move line down 
Shift + ->: Next Tab    
Shift + <-: Previous Tab
{highlight_end}
]]
```

Hopefully, by making these two changes, you should have the functionality you would like

As for the `greeting_message`, you can put that as you wish. This is just the message you see on starting Ox.

The default greeting message is now

```lua
-- Configure Greeting Message --
greeting_message.enabled = true
greeting_message.format = [[
Ox Editor v{version}
The simple but flexible text editor
{highlight_start}
Quick Start Guide:

Ctrl + Q:  Quit        
Ctrl + N:  New File    
Ctrl + O:  Open File   
Ctrl + S:  Save File   
Alt  + S:  Save File As
Ctrl + H:  Help Message

Ready?
Start Typing
{highlight_end}
]]
```
