### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Dominiquini** [curlpipe/ox#166]
**Describe the bug**
The app crashs when startup

**To Reproduce**
1. Install the package ox-bin from aur (https://aur.archlinux.org/packages/ox-bin)
2. Check if is the version 0.6.3
3. Start the app on the terminal: ox

**Expected behavior**
Editor should start!

**Log**
```
Lua(RuntimeError("[string \"src/main.rs:54:9\"]:18: module 'src/plugin/networking' not found:\n\tno field package.preload['src/plugin/networking']\n\tno file '/usr/local/share/lua/5.4/src/plugin/networking.lua'\n\tno file '/usr/local/share/lua/5.4/src/plugin/networking/init.lua'\n\tno file '/usr/local/lib/lua/5.4/src/plugin/networking.lua'\n\tno file '/usr/local/lib/lua/5.4/src/plugin/networking/init.lua'\n\tno file './src/plugin/networking.lua'\n\tno file './src/plugin/networking/init.lua'\n\t\n\tcan't load C modules in safe mode\nstack traceback:\n\t[C]: in ?\n\t[C]: in function 'require'\n\t[string \"src/main.rs:54:9\"]:18: in main chunk"))
stack backtrace:
   0:     0x570c69523975 - <unknown>
   1:     0x570c6954921b - <unknown>
   2:     0x570c69520c0f - <unknown>
   3:     0x570c69524cc1 - <unknown>
   4:     0x570c6952499c - <unknown>
   5:     0x570c69525321 - <unknown>
   6:     0x570c69525187 - <unknown>
   7:     0x570c69523e39 - <unknown>
   8:     0x570c69524e14 - <unknown>
   9:     0x570c69288de3 - <unknown>
  10:     0x570c693697f4 - <unknown>
  11:     0x570c69397753 - <unknown>
  12:     0x570c6938bc69 - <unknown>
  13:     0x570c6951bd20 - <unknown>
  14:     0x570c6936b635 - <unknown>
  15:     0x76417aadee08 - <unknown>
  16:     0x76417aadeecc - __libc_start_main
  17:     0x570c69289551 - <unknown>
  18:                0x0 - <unknown>
```

**Desktop (please complete the following information):**
 - OS: CachyOS (Linux CachyOS 6.10.5-1-cachyos #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 13:26:56 +0000 x86_64 GNU/Linux)

-- The previous version (6.1.2) works fine!
-- The bug also happens on the binary version downloaded from the releases page on GitHub!

Thanks.

**Comment by curlpipe** [comment]
I've just realised this myself - already fixed locally, will publish an emergency release ASAP

**Comment by curlpipe** [comment]
0.6.4 released which contains a fix - should be up on the AUR now

Turns out the binary for 0.6.3 didn't work outside my build environment :facepalm:
