### ISSUE TITLE
Configuration File

### ISSUE THREAD

**Issue by curlpipe** [curlpipe/ox#17]
**Is your feature request related to a problem? Please describe.**
Good text editors allow for extensibility and customizability. The ability to change the colours and functionality is not only fun but also allows room for a community to build.

**Describe the solution you'd like**
Have a TOML file in some directory somewhere and have Ox read it and apply it.

**Describe alternatives you've considered**
At the moment, Ox is suckless with a config.rs but that is daunting for newcomers and a toml file will be much more appreciated probably. (Also reads better!)

**Comment by Diwakar-Gupta** [comment]
## Loading of config file
 @curlpipe 
https://github.com/curlpipe/ox/blob/086f66532f053c0feeffa94b92b9ebfd3e9feb33/src/main.rs#L114-L121
if config file location returned by above function does not exist then should we try loading `~/.config/ox/ox.ron`.

https://github.com/curlpipe/ox/blob/086f66532f053c0feeffa94b92b9ebfd3e9feb33/src/main.rs#L76

currently `ox` is not checking if `base_dirs.config_dir() /ox/ox.ron` does not exist.
