### ISSUE TITLE
Intallation error

### ISSUE THREAD

**Issue by MustangBro7** [curlpipe/ox#171]
**What is the bug?**
Issue when downloading

**Screenshots (if applicable)**

![image](https://github.com/user-attachments/assets/db407093-6c01-4670-a966-f44eaa85998c)

**Comment by curlpipe** [comment]
Ah, I see what's happened here.
Hopefully this should be patched now.
Let me know if it works.

**Comment by MustangBro7** [comment]
Yup worked , Thank You :)
