### ISSUE TITLE
some regression test failure with 0.6.9 rel build

### ISSUE THREAD

**Issue by chenrui333** [curlpipe/ox#178]
👋 while bumping [ox to 0.6.9 release](https://github.com/Homebrew/homebrew-core/pull/195804), ran into some regression test failure, as `ox test.txt` does not populate the test.txt file (while it does work for me in my local), not sure what might be the cause, raise the issue in here for ideas. Thanks!

**Comment by curlpipe** [comment]
That is strange. Is there a way I can run these tests locally on my machine? I am happy to try finding the offending commit and work to fix it.

**Comment by chenrui333** [comment]
it might be just test issue, as it works fine for me in my local as well.

**Comment by chenrui333** [comment]
I just removed the test and see how it goes.

**Comment by curlpipe** [comment]
Great, thanks!
