### ISSUE TITLE
Auto Theme. 

### ISSUE THREAD

**Issue by plyght** [curlpipe/ox#184]
I would like to see a 'default' theme, sort of like Micro's "simple" theme that takes from the term's colors and uses those: 

[Micro Theming Docs](https://github.com/zyedidia/micro/blob/master/runtime/help/colors.md#colors)
> 16-color: A colorscheme that uses the 16 default colors will always work but will only look good if the 16 default colors have been configured to the user's liking. Using a colorscheme that only uses the 16 colors from the terminal palette will also preserve the terminal's theme from other applications since the terminal will often use those same colors for other applications. Default colorschemes of this type include simple...

[simple.micro](https://github.com/zyedidia/micro/blob/master/runtime/colorschemes/simple.micro): `color-link comment "blue"
color-link constant "red"
color-link identifier "cyan"
color-link statement "yellow"
color-link symbol "yellow"
color-link preproc "magenta"
color-link type "green"
color-link special "magenta"
color-link ignore "default"
color-link error ",brightred"
color-link todo ",brightyellow"
color-link hlsearch "black,yellow"
color-link statusline "black,white"
color-link indent-char "black"
color-link line-number "yellow"
color-link current-line-number "red"
color-link diff-added "green"
color-link diff-modified "yellow"
color-link diff-deleted "red"
color-link gutter-error ",red"
color-link gutter-warning "red"
#Cursor line causes readability issues. Disabled for now.
#color-link cursor-line "white,black"
color-link color-column "white"
#No extended types. (bool in C)
color-link type.extended "default"
#No bracket highlighting.
color-link symbol.brackets "default"
#Color shebangs the comment color
color-link preproc.shebang "comment"
color-link match-brace ",magenta"
color-link tab-error "brightred"
color-link trailingws "brightred"`

**Comment by curlpipe** [comment]
Yeah, that should be possible.

I can add a theme called something like `default16` that uses the terminal's colours.

**Comment by curlpipe** [comment]
I'm currently working on 0.7.2, which is taking a little longer than expected (will probably be released some time in the next two weeks).

I'm planning to release this in 0.7.3, which should be a smaller update.

So all in all, I think it'll be released no longer than in the next month.

**Comment by plyght** [comment]
> I'm currently working on 0.7.2, which is taking a little longer than expected (will probably be released some time in the next two weeks).
> 
> I'm planning to release this in 0.7.3, which should be a smaller update.
> 
> So all in all, I think it'll be released no longer than in the next month, more likely in around 2-3 weeks.

@curlpipe Awesome!

Unfortunately, that is what is preventing me from using Ox instead of Micro. Once 0.7.3 is released, I'll happily switch over!

**Comment by curlpipe** [comment]
I've started working on this a bit

It uses the default 16 colours

Here is what it looks like on two different example terminal configurations:

<div style="display: inline;">
<img width="400" src="https://github.com/user-attachments/assets/a099470c-821f-4797-96ce-2288874cab92">
<img width="400" src="https://github.com/user-attachments/assets/d4d3d4b3-3a0a-4fd4-81e2-dc31db293005">
</div>

It will look different on each terminal due to the different configurations people have. It looks mostly alright on several themes I've tried.

Still have some work to do to integrate this with the editor, but it's in progress!

If you have any comments on it, feel free to let me know.

**Comment by curlpipe** [comment]
I implemented this in `0.7.3`

To activate `default16` (the theme) I recommend running `ox --config-assist`, selecting the theme, and then after the set-up process, that should give you an editor that uses the default 16 colours the terminal provides.

Closing for now, if there are any further improvements or suggestions - feel free to let me know and this can be reopened.
