### ISSUE TITLE
lost nushell syntax highlight

### ISSUE THREAD

**Issue by kurokirasama** [curlpipe/ox#189]
**What is the bug?**
In the latest version, 0.7.4, syntax highlighting for [nushell](https://github.com/nushell/nushell) doesn't work. Even with `-f nu`

**What did you do to get the bug?**

Just open a proper .nu file

**What behaviour were you expecting?**

syntaxk highlighting

**Screenshots (if applicable)**

**Comment by curlpipe** [comment]
Thanks for pointing this out, this probably happened when I changed around how file types worked.
I don't know how I managed to miss it!

I've implemented complete nushell support, which is waiting to be released in 0.7.5, which should be released in the next few days.

**Comment by kurokirasama** [comment]
it is fixed! Thanks!
