### ISSUE TITLE
Mouse integration

### ISSUE THREAD

**Issue by curlpipe** [curlpipe/ox#21]
**Is your feature request related to a problem? Please describe.**
The transition from a graphical text editor to a text based one is not an easy task. There is usually a huge learning curve. To ease that learning curve, mouse integration will allow Ox to be used just like a normal text editor.

**Describe the solution you'd like**
Add the ability to interact with the mouse by allowing mouse selection and moving the cursor when clicking the mouse. 

**Describe alternatives you've considered**
Vim style selection (but after using that for a year and a half, I don't want to touch it ever again).

**Comment by Eragonfr** [comment]
I'm not sure that this is related to mouse.
But if you're implementing mouse selection in ox.
Can we have selection support using the keyboard (and oxa in the same time), please.

**Comment by curlpipe** [comment]
Basic mouse functionality has been added to 0.5.0 (for selecting documents in the tab line and jumping to places within the document)

Closing this and leaving #51 open for the mouse selection part, which is not yet ready.
