### ISSUE TITLE
Support for custom config directories set with the XDG_CONFIG_HOME variable.

### ISSUE THREAD

**Issue by mmatongo** [curlpipe/ox#27]
**Is your feature request related to a problem? Please describe.**

I like to keep my configurations all in one place. I have a custom directory for the `XDG_CONFIG_HOME` variable set because it helps with that. However I noticed that [ox](https://github.com/curlpipe/ox) doesn't respect this and doesn't look at my custom directory set at the `XDG_CONFIG_HOME` variable.

**Describe the solution you'd like**

I would like to see support for custom directories set using the `XDG_CONFIG_HOME` variables.

**Describe alternatives you've considered**

The only alternative I have considered currently is creating a symbolic link;
`ln -s $XDG_CONFIG_HOME/ox/ox.toml $HOME/.config/ox/ox.toml`

**Comment by curlpipe** [comment]
That shouldn't be too hard to implement, i'll add that as something to add to the next version :+1:

**Comment by thomaseizinger** [comment]
You may want to consider using https://docs.rs/directories/3.0.1/directories/ for this! It abstracts this behaviour away for major platforms :)

**Comment by curlpipe** [comment]
I have just implemented this using the directories library to allow for Windows, MacOS and Linux Support. Thank you very much :smile:.

**Comment by mmatongo** [comment]
Thank you 🙏
