### ISSUE TITLE
Syntax highlighting theme

### ISSUE THREAD

**Issue by RemiIia** [curlpipe/ox#31]
Can you write what kind of theme you are using in ox or give its specification so that I can port it to my editor? @curlpipe 
![image](https://user-images.githubusercontent.com/33205215/95679579-63ccaa00-0bdc-11eb-9d63-000b6d00c2e2.png)

**Comment by curlpipe** [comment]
Hello! I made this theme by myself and I will happily give you the RGB colour values for it.

Background: 41, 41, 61
Text colour: 255, 255, 255
Status line background: 59, 59, 84
Status line text colour: 35, 240, 144
Line number text colour: 65, 65, 98

Comments: 113, 113, 169
Keywords: 134, 76, 232
Strings: 39, 222, 145
Characters: 40, 198, 232
Digits: 40, 198, 232
Booleans: 86, 217, 178
Functions: 47, 141, 252
Structs: 47, 141, 252
Macros: 223, 52, 249
Attributes: 40, 198, 232

**Comment by RemiIia** [comment]
Thank you!
