### ISSUE TITLE
Backspace at position 0:0 incorrectly deletes characters ahead

### ISSUE THREAD

**Issue by MikeGlennFWC** [curlpipe/ox#36]
While the cursor is at the very beginning of a file, when pressing backspace, it should do nothing, but instead it deletes the characters ahead of the cursor.

**Comment by curlpipe** [comment]
Thanks for pointing this out! I'll get to fixing this in the next release.

**Comment by curlpipe** [comment]
Fixed this in the branch `0.2.6` for the next release :+1:
