### ISSUE TITLE
Icon does not shows on default install of windows terminal (WSL)

### ISSUE THREAD

**Issue by rizkyramadhan** [curlpipe/ox#38]
**Describe the bug**
open any file, and icons is shown as squares.....

**Screenshots**
![image](https://user-images.githubusercontent.com/126301/97949774-4f3c9580-1dc7-11eb-8ff9-336448fe2bda.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (WSL Ubuntu 20.04.01)

**Comment by pixelr0** [comment]
same here, we are probably missing a font but which one?

**Comment by curlpipe** [comment]
Ox uses NerdFonts for the icons.

**Comment by vlisivka** [comment]
Same on Fedora 32 in mate terminal:  is shown, while 並 﫦  are not.

![Screenshot_2020-11-03_15:36:04](https://user-images.githubusercontent.com/4396623/97991606-5759fc80-1dea-11eb-9cf9-59a4f791f916.png)

**Comment by curlpipe** [comment]
https://www.nerdfonts.com/

Install NerdFonts from here, or through your distro package manager and it should hopefully work, you might have to add the font to your terminal emulator.

**Comment by vlisivka** [comment]
With Nerd font, the problem is gone.

![Screenshot_2020-11-03_18:41:27](https://user-images.githubusercontent.com/4396623/98014546-72d20100-1e04-11eb-9318-f0c952efe1d6.png)

**Comment by curlpipe** [comment]
:)
