### ISSUE TITLE
Default Editor Theme on Mac

### ISSUE THREAD

**Issue by MatthewC221** [curlpipe/ox#39]
**Describe the bug**
Is there an issue with the default theme? It is a weird tint of red so I'm assuming this is not intentional. 

**To Reproduce**
Steps to reproduce the behavior: Followed the steps of the README to install using homebrew.

**Screenshots**
![image](https://user-images.githubusercontent.com/24473096/97950512-334aeb00-1deb-11eb-8f3e-df1ea775b01e.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 64bit

**Comment by bcullman** [comment]
came here to note I am seeing the same. macOS 10.15.7

**Comment by uemit** [comment]
Same here on macOS Big Sur 11.0.1 Beta (20B5012d)

**Comment by curlpipe** [comment]
Hmm. Interesting. I haven't really tested it on macOS yet but I will try to investigate this problem.

**Comment by martykan** [comment]
The problam is the default Terminal.app doesn't support true 24bit color, only ANSI color. 
It works fine in iTerm2.

**Comment by curlpipe** [comment]
Thanks @martykan
I guess I'll add fallback colours to stop the strange red and make it black instead.

**Comment by Inevix** [comment]
have the same issue. Catalina 10.15.7.
![image](https://user-images.githubusercontent.com/28815318/98704039-d91ace80-2384-11eb-8160-ce504e571fb2.png)

**Comment by Inevix** [comment]
solution has been found but I didn't understand how to enable a syntax highlighting
![image](https://user-images.githubusercontent.com/28815318/98704786-ba690780-2385-11eb-8df6-fc472a443f3d.png)
![image](https://user-images.githubusercontent.com/28815318/98704818-c5239c80-2385-11eb-8214-1a03a4d46583.png)

**Comment by curlpipe** [comment]
I've added a 16 bit fallback colour scheme in 0.2.7, hopefully on macOS's terminal.app and other terminals that don't support true 24 bit colours, Ox won't look like the depths of hell.

**Comment by Inevix** [comment]
@curlpipe in homebrew only 0.2.5 is available
https://formulae.brew.sh/formula/ox#default

**Comment by curlpipe** [comment]
@invenix I don't maintain the homebrew package unfortunately. I might have to see if I can transfer ownership.

**Comment by kazzkiq** [comment]
Just installed Ox via homebrew and ended up with the same issue.

![Screen Shot 2020-11-13 at 10 20 52](https://user-images.githubusercontent.com/1953194/99076590-23c16400-259a-11eb-84f1-002bf41063c7.png)


Since homebrew is the widespread solution for macOS installs, I guess it would be wise to update it to `0.2.7` as fast as possible to prevent users from thinking the editor is "broken" and dropping it before even trying.

**Comment by curlpipe** [comment]
@kazzkiq Working on transferring ownership. At the moment, only 0.2.6 is out and 0.2.7 is still in the works.
