### ISSUE TITLE
Change default keyboard shortcut with config

### ISSUE THREAD

**Issue by jashsayani** [curlpipe/ox#42]
**Is your feature request related to a problem? Please describe.**
Change default keyboard shortcut with config (specially Ctrl + W)

**Describe the solution you'd like**
Change Ctrl + W to something else. It will drive MacOS users mad, because Ctrl + W is "Close Tab" on MacOS and I keep pressing it to close tab but end up in "Save As". Also, `Esc` does not get me out of "Save As".

**Describe alternatives you've considered**
None.

**Comment by curlpipe** [comment]
I've been working on this for the last couple of days and am almost ready to release it with 0.2.6 👍

**Comment by jashsayani** [comment]
Nice! thanks for the update.

**Comment by curlpipe** [comment]
Implemented in 0.2.6, there is a new wiki which can teach you how to do this: https://github.com/curlpipe/ox/wiki
You might need to update your configuration file as there are a couple of rearrangements and improvements but hopefully it won't be too difficult, especially with the new wiki which is hopefully thorough enough.
👍
