### ISSUE TITLE
False claims of being "fast", terrible design unable to handle files with long lines

### ISSUE THREAD

**Issue by bill-myers** [curlpipe/ox#46]
According to https://news.ycombinator.com/item?id=24976905, ox can't handle a file with a 1GB long line.

Obviously when you design a new editor, handling such files is the most important thing, since it means that you have properly designed the editor's algorithms and data structures.

Clearly you failed completely at the most basic task and showed utter lack of competence in the design of algorithms and data structures.

Also, the program is falsely advertised as "fast", when instead it should be described as "unusably slow", misleading users into thinking this is well-written software.

**Comment by Ygg01** [comment]
If you're gonna complain, at least have the courtesy of demonstrating how it's slow.

For example:

When running:

     base64 /dev/urandom | head -c 1000000000 > file.txt

I expect to open it in few seconds.
It opened in a few minutes.

**Comment by gabssnake** [comment]
compare with vim

**Comment by Ygg01** [comment]
> compare with vim

On what axis, in which way? When openining what? How? 

You might as well as said, compare with chromium.

**Comment by curlpipe** [comment]
When I said "fast", Ox was quite minimal recently, I've added many features and have therefore slowed it down. I plan in the very near future to optimise these features. Ox is still a work in progress and I don't recommend using it as a main editor, this is really just a personal project of mine and is in no way comparable to the mighty vim.

**Comment by Ygg01** [comment]
@curlpipe it got top spot on HN, and I think people are taking that little blurb waaaaaaaaaaaay too seriously.

**Comment by curlpipe** [comment]
issue #45 more constructive

**Comment by gabssnake** [comment]
> On what axis, in which way? When openining what? How?

Oh, meant no offense and wasn't clear. Was pointing out that one could compare your given code sample in both ´ox´ and ´vim´ to determine relative fastness or slowness.

If one where to claim that something is "fast", invariably, that is in comparison to something else.
Could be compared to Sublime Text, or VS Code, or whatnot. Just happen to like ´vim´.

Also a HN visitor, coming from Twitter, sucking at politeness. Good day.
