### ISSUE TITLE
Accept line number and column number in file name

### ISSUE THREAD

**Issue by vlisivka** [curlpipe/ox#47]
**Is your feature request related to a problem? Please describe.**
Sometimes, I need to jump to a line in a source file, e.g. from backtrace listing. 

**Describe the solution you'd like**
De facto convention for the line number is FILE_NAME:LINE_NUMBER[:COLUMN_NUMBER] . For example, mceditor/mcviewer (part of Midnight Commander) can open such file and jump to the line number.

Example: `main.c:5:4`

**Describe alternatives you've considered**
Open the file, then navigate to the line, e.g. by pressing Ctrl-J to jump to line/char.

**Comment by curlpipe** [comment]
This shouldn't be too hard to implement, I'll take a look into it. What do you think should happen if a line number that is over the length of the document (e.g. A document is 100 lines long and I put in document.txt:200)?

**Comment by vlisivka** [comment]
In this case, cursor should be at the last line of the file.

**Comment by pymaldebaran** [comment]
> This shouldn't be too hard to implement, I'll take a look into it. What do you think should happen if a line number that is over the length of the document (e.g. A document is 100 lines long and I put in document.txt:200)?

Just like @vlisivka I think in this case it should place the cursor at the last line of the file. But I think it should also display a little warning to the user "requested position ll:cc is out of file".

You can also consider the case where the requested line exists but not the requested column in this line --> it should place the cursor at the end of the requested line and display a relevent warning to the user "requested column cc does not existe for line ll."

**Comment by curlpipe** [comment]
@pymaldebaran Good idea, I'll do that.

**Comment by curlpipe** [comment]
I've now managed to get it to take in filenames like this
`test.txt:row:column`
and
`test.txt:row`
and
`test.txt`
Just need to implement bound checking and display that warning message, shouldn't be too difficult.

**Comment by curlpipe** [comment]
Done 🎉  This should come out in a week or two with 0.2.7.
![image](https://user-images.githubusercontent.com/11898833/98596399-4bc97280-22cf-11eb-8d07-86b68a7fc20f.png)
![image](https://user-images.githubusercontent.com/11898833/98596434-571c9e00-22cf-11eb-929b-6fe94ec72d6c.png)
