### ISSUE TITLE
Windows linebreaks not supported?

### ISSUE THREAD

**Issue by mspreij** [curlpipe/ox#49]
Environment: Windows 10 with WSL. Installed rustc/cargo without issues as per instructions.

When I opened a 3 line file to test it out, it seemed to just hang/pause after I hit enter on the command line.
Didn't manage to abort, Ctrl-C or anything, killall ox worked from another window.
After testing a few things, turns out when I converted the linebreaks to unix format it worked fine, but unix2dos made it hang again.

ps. was there any log I could have looked at, or something else I could have checked/tried?
Not really deep into software engineering..

**Comment by curlpipe** [comment]
Debugging Ox is a pain. I should really add a logging file to it, you are right. I'll experiment with this and let you know if I'm able to recreate the issue.

**Comment by mspreij** [comment]
Rocking :-) let me know if there's anything I can do.

**Comment by curlpipe** [comment]
I've added a log file to Ox and have now concluded that the reason is 100% because of the dos line endings. I have now fixed this (afaik). It should be out in 0.2.7.  Thanks for the report :)
