### ISSUE TITLE
Can't install dependencies on WSL2 Ubuntu 20.04.1

### ISSUE THREAD

**Issue by adriaanbd** [curlpipe/ox#50]
**Describe the bug**
When running the command specified to install dependencies for other distros and using WSL2 with Ubuntu 20.04.1, system returns `sh: 0: Can't open /usr/bin/rustup`.

**To Reproduce**
Run `$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh /usr/bin/rustup toolchain install stable`

**Expected behavior**
Expected dependencies to install

**Screenshots**

From clipboard:

```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh /usr/bin/rustup toolchain install stable
sh: 0: Can't open /usr/bin/rustup
curl: (23) Failed writing body (0 != 15974)
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro using WSL2 Ubuntu 20.04.1 LTS (GNU/Linux 4.19.104-microsoft-standard x86_64)

**Comment by curlpipe** [comment]
Looks like Rust failed to install. If you don't have Rust installed already, you can use the official website to try and install it from the official instructions https://www.rust-lang.org/tools/install

**Comment by adriaanbd** [comment]
Thank you! I did that and Ox opens up an empty editor with `$ ox`

**Comment by curlpipe** [comment]
:)
