### ISSUE TITLE
Selection support

### ISSUE THREAD

**Issue by ghost** [curlpipe/ox#51]
Currently only editing feature I miss is text selection with shift-arrows and copy and pasting using ctrl-c, ctrl-v. These shortcuts are standard ones and they are in line with Ox philosophy of using standard shortcuts.

**Comment by curlpipe** [comment]
This is definitely something I want to add, I'd want to make Ox more efficient and rewrite it in `Crossterm` before adding this but this is most definitely the next feature I want to add. :)

**Comment by Trismegistos84** [comment]
That is very good news. Good user friendly console editor will definitely
find many fans.

wt., 3 lis 2020, 18:38 użytkownik curlpipe <notifications@github.com>
napisał:

**Comment by HKalbasi** [comment]
Any news on this?

**Comment by curlpipe** [comment]
Hi @HKalbasi, it looks like this might not be implemented for a while as there are some more pressing things I need to focus on e.g. bug fixing

**Comment by curlpipe** [comment]
Just saw the PR, I might actually shift up mouse support in that case. I want to do a few bug fixes (I didn't realise how broken search and replace was :grimacing: but after some of these basic fixes, I'll get straight to getting a basic form of mouse support with selection up and running!)

**Comment by HKalbasi** [comment]
How about you fix the bugs and I implement the selection? Ox is my dream terminal editor, I always wished about a non-modal, "normal" editor in the terminal that I can use over ssh. So I'm willing to put work on making it reality. Bugs are equally important for making the editor usable and I don't want to deprioritise them.

**Comment by curlpipe** [comment]
That sounds great, I'm happy to crack on with the bugs!

**Comment by curlpipe** [comment]
Implemented!
