### ISSUE TITLE
ox file hangs forever

### ISSUE THREAD

**Issue by adriaanbd** [curlpipe/ox#53]
**Describe the bug**
When opening a file from root folder with the `ox file` command, the terminal hangs and it's impossible to exit.

**To Reproduce**

Execute: 

```
$ cd project/folder
$ ox main.tf
```

**Expected behavior**
Expected an editor to open and load the file, similar to executing `ox` by itself.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro using WSL2 Ubuntu 20.04.1 LTS (GNU/Linux 4.19.104-microsoft-standard x86_64)

**Comment by curlpipe** [comment]
I fixed this. This was due to dos line endings. The patch should come out with 0.2.7, thank you for the report

**Comment by adriaanbd** [comment]
When is it scheduled to be released? I tried doing a cargo install at `ox/tree/0.2.7` but it failed:

```
$ cargo install --git https://github.com/curlpipe/ox/tree/0.2.7
    Updating git repository `https://github.com/curlpipe/ox/tree/0.2.7`
warning: spurious network error (2 tries remaining): unexpected http status code: 404; class=Http (34)
warning: spurious network error (1 tries remaining): unexpected http status code: 404; class=Http (34)
error: failed to clone into: /home/adriaanbd/.cargo/git/db/0.2.7-3b63156f91cb77a4

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  unexpected http status code: 404; class=Http (34)
```

**Comment by curlpipe** [comment]
It probably is best if you don't install 0.2.7 just yet, it's still in progress but I am making significant progress with the rest of the changes and fixes I want to implement. It'll probably be done by the end of the week or worst case scenario, in just over a week. Although I'm ahead of schedule. I'll try to remember to ping you when it's ready :)

**Comment by curlpipe** [comment]
Let me know if you are really desperate to try it out and I can give you a file with unix line endings to open in a currently released version of Ox. :) I'll be more than happy to assist.

**Comment by adriaanbd** [comment]
I wouldn't want to distract you from the release. If its quick and easy it would be nice, but I can wait :) Thanks a lot though!
