### ISSUE TITLE
Support more shortcuts?

### ISSUE THREAD

**Issue by eclipseo** [curlpipe/ox#56]
Not specifically lake vim, but things li'e dd to erase a line, or some shortcut to erase a word or replace it would be useful.

Thanks.

**Comment by curlpipe** [comment]
Working on this at the moment, hope to release it in the next few days.

**Comment by curlpipe** [comment]
I've added the ability to erase a line but as for the erasing a word, I haven't added that just yet. I'll probably get round to that in the next update now that the infrastructure has been added. I'll try to keep you posted.

**Comment by curlpipe** [comment]
Well the update took longer than expected, but I've now added the ability for more key bindings. You can check out the wiki to learn how you can change your configuration files to add more functionality, and also check out the new functionality that I have added.
Let me know if there are any issues.
