### ISSUE TITLE
v0.2.6 broken

### ISSUE THREAD

**Issue by tim77** [curlpipe/ox#62]
**Describe the bug**
After update 0.2.5 -> 0.2.6 `ox` doesn't work anymore.

**To Reproduce**
Try to run new `ox`.

```sh
$ ox
```

```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: Message("missing field `status_left`"), position: Position { line: 0, col: 0 } }', src/config.rs:67:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    17096 IOT instruction (core dumped)  ox 1.txt
```

**Desktop (please complete the following information):**
 - OS: Fedora 33

**Comment by DeadMozay** [comment]
Same problem openSUSE, full backtrace

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: Message("missing field `status_left`"), position: Position { line: 0, col: 0 } }', src/config.rs:60:39
stack backtrace:
   0:     0x55f174ca08b6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4c4ddd0ddbec2967
   1:     0x55f174c27a0c - core::fmt::write::hf3eaaed4ead9a783
   2:     0x55f174c9fe66 - std::io::Write::write_fmt::h8bc2722773da3692
   3:     0x55f174c9f92a - std::panicking::default_hook::{{closure}}::hb4aa7713506bbc92
   4:     0x55f174c9f1a7 - std::panicking::rust_panic_with_hook::h3bae7bb0170c53e4
   5:     0x55f174c9ee3a - rust_begin_unwind
   6:     0x55f174c25350 - core::panicking::panic_fmt::h61b0069a9292063e
   7:     0x55f174c28a32 - core::option::expect_none_failed::h3fe325d90c0e4e54
   8:     0x55f174bacb75 - ox::editor::Editor::new::ha87ad7fb7a20327c
   9:     0x55f174bc7701 - ox::main::hf604d4af70078c34
  10:     0x55f174ca9693 - std::sys_common::backtrace::__rust_begin_short_backtrace::h233e86bd7295977c
  11:     0x55f174bd1b1a - main
  12:     0x7f930f47b152 - __libc_start_main
  13:     0x55f174b8719e - _start
  14:                0x0 - <unknown>
`

**Comment by curlpipe** [comment]
whoops, I know what went wrong here. I ought to test more thoroughly. I'll issue a fix soon.

**Comment by curlpipe** [comment]
I've issued a patch for this just now, you should be able to download the deb or rpm or binary or clone master and build it from there. The issue was that there were some changes to the configuration file and I didn't update the hardcoded configuration file, causing a panic when reading it. You can check out the wiki pages to see the new configuration format or you can use the defaults if you wish.

**Comment by tim77** [comment]
Thanks for quick fix.

**Comment by vladimyr** [comment]
@curlpipe I've noticed that you patched master but the 0.2.7 branch (b7f5d91) still fails. ⚠️ 

Running following command:
```bash
echo -n "commit: "; git rev-parse --short HEAD; target/release/ox --version; target/release/ox
```
results in:
```
commit: b7f5d91
Ox 0.2.7
panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: InvalidEscape("Unknown escape character"), position: Position { line: 171, col: 39 } }', src/config.rs:71:14
```

**Comment by curlpipe** [comment]
Yes, that is intentional. When it's ready, that won't be a problem. :)

**Comment by chenrui333** [comment]
just heads up, ox 0.2.7 still does not work.

**Comment by curlpipe** [comment]
Damn. I really ought to change the configuration system, it's awful.
