### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by rizrmd** [curlpipe/ox#70]
Ox is promising!

Do you plan to support some kind of plugin system? This will create an ecosystem to make ox thrive. 

I think [bevyengine](https://bevyengine.org/) ECS is wonderful, where everything is a plugin - even the renderer itself is a plugin, but it may be too different from ox architecture. What do you think ?

**Comment by curlpipe** [comment]
This is one of the last things I plan to do, but I am slowly working towards it. Last update included a language that allowed control of the editor (it's very basic though). After I've developed the language a bit more I reckon this would be possible.

**Comment by rizkyramadhan** [comment]
Sounds great!

Creating new scripting language would make newcomer not too overwhelmed with rust. But also is another level of complexity.

Do you think adopting established language runtime, such as lua or or maybe js will improve ox  extensiblity ?

**Comment by rizkyramadhan** [comment]
Also there are benefit of writing plugin in rust, which will make the plugin safe and fast as ox did. But will increase barier to entry for newcomer.

**Comment by curlpipe** [comment]
I'd actually really like to split Ox into a backend and a front end some time in the far future, that would make it really really easy to modify and configure.

**Comment by rizkyramadhan** [comment]
I think module system ala vscode is better because it would not force something to be categorized into backend or frontend. What if  some functionality shared between frontend and backend ? where do we put those ?

**Comment by curlpipe** [comment]
Plugin system was implemented in the new rewrite using Lua. Documentation is available in the wiki [here](https://github.com/curlpipe/ox/wiki/Configuration)
