### ISSUE TITLE
Sudo support

### ISSUE THREAD

**Issue by Nainterceptor** [curlpipe/ox#72]
**Is your feature request related to a problem? Please describe.**
Everytime that I've to write a file somewhere i don't have rights, like `ox /etc/hosts`, write is failing because I'm stupid and I've forgotten to prepend with `sudo`.

**Describe the solution you'd like**
In VIM, I'm able to write `:w !sudo tee % > /dev/null` to enter password then write to file, I guess that you'll not be able to add infinite shortcuts, so maybe a shortcut to enter "custom commands" where a command will prompt for sudo ? Maybe dangerous for user exeperience while sudo is not installed & configured everywhere, maybe it can be a plugin in upcoming plugin system ?

**Describe alternatives you've considered**
Use Ctrl + W to write in another place, then use `sudo mv`

**Comment by curlpipe** [comment]
0.2.6 has a new command mode. Saving as root is something I am looking in to and I could certainly do this.

**Comment by curlpipe** [comment]
I have just released 0.2.7 and wrote a built in macro that will allow you to use the command of `save #` in the file, this uses a bash command behind the scenes to do this.
You can access this command by using the binding of `Alt + A` and then typing `save #` and pressing enter.
Hopefully this is a good solution to the problem.
