### ISSUE TITLE
Alt + arrows

### ISSUE THREAD

**Issue by Nainterceptor** [curlpipe/ox#73]
**Is your feature request related to a problem? Please describe.**
When I'm writing things, it's quicker to move cursor to use Alt + Arrows, to move word-by-word.

**Describe the solution you'd like**
In my .zshrc I've the following bindkey :
```
bindkey -e
bindkey '[C' forward-word
bindkey '[D' backward-word
```
I think that nobody use this key combination to write `[C` or `[D` to file, so maybe it can be supported by default ?

**Describe alternatives you've considered**
Be able to add kind of bindkey somewhere ?

**Comment by curlpipe** [comment]
There is a keybinding section in the config file in  0.2.6 but it's not very complete. I'm working on adding more keys to it.

**Comment by marekhanzlik** [comment]
I would love to have it as default behaviour cause it's a standard in text navigation nowadays
but IMHO this should be on CTRL+arrows as it's standard (almost every other editor, chrome, vscode etc..)

**Comment by Nainterceptor** [comment]
> but IMHO this should be on CTRL+arrows as it's standard (almost every other editor, chrome, vscode etc..)

It's ALT+arrows on my jetbrains IDE by default (on macOS), ALT+up to select more content, ALT+down to select less content
Alt+Shift+Up/down to move whole line up/down

**Comment by marekhanzlik** [comment]
Hmm, shortcuts in Intellij looks really weird to me
Why use ALT+UP to select more content when you can use SHIFT+UP which work in every textbox ever
using SHIFT+ALT+UP for moving whole lines looks cumbersome and now that ALT+UP is freed by SHIFT, you can use it for simpler line movement

the shortcuts in intellij looks realy non standard and i've never encounter those yet
CTRL for moving by work and ALT for line change i've seen in numerous different editors (either online or offline ones) so i look at them as more or less of a standard

**Comment by curlpipe** [comment]
This is done, you can now check the wiki https://github.com/curlpipe/ox/wiki in order to learn how to use the new and improved keybindings. You can add this to your configuration file.

Here is an example of moving around words:
```
Alt(Left): ["move word left"],
Alt(Right): ["move word right"],
```

I've added it to my config and it works well.
