### ISSUE TITLE
Delete button

### ISSUE THREAD

**Issue by Nainterceptor** [curlpipe/ox#74]
**Is your feature request related to a problem? Please describe.**
When I tap text, to delete the content before the cursor, I use backspace, to delete content after the cursor, I want to use delete button (ASCII 127, DEL)

**Describe the solution you'd like**
When I tap the delete button, it should delete the character on the right of the cursor

**Describe alternatives you've considered**
Use right arrow then backspace, but it's painful when you're really using the editor imo.

**Comment by curlpipe** [comment]
Should be implemented in version 0.3.1 and up
