### ISSUE TITLE
Can we select the language for syntax highlighting via the CLI?

### ISSUE THREAD

**Issue by davidalsh-rokt-zz** [curlpipe/ox#76]
**Is your feature request related to a problem? Please describe.**
Can we add a way to select the language to apply syntax highlighting to?

**Describe the solution you'd like**
Perhaps a simple method of running the command like
```
ox --lang sh ~/.zshrc
```

**Describe alternatives you've considered**
Using the configuration
```
ox --config ~/.zshrc_ox.ron ~/.zshrc
```
But I couldn't find the configuration schema and also it can get a little annoying if there is a config for every extension

**Comment by curlpipe** [comment]
Brilliant idea

**Comment by curlpipe** [comment]
Can be done in version 0.3.2 and up using the `--filetype` or `-f` option and providing the file extension e.g. `rs` for rust or `sh` for a shell script

e.g. `ox -f sh .zshrc`
