### ISSUE TITLE
panicked at 'index out of bounds: the len is 0 but the index is 0', src/document.rs:385:21

### ISSUE THREAD

**Issue by jdelgadoalfonso** [curlpipe/ox#77]
**Describe the bug**
Edit an empty buffer causes a panic.

**To Reproduce**
1. Execute ox with no parameters.
2. Press backspace key twice.
3. The application panics showing
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/document.rs:385:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    713693 abort (core dumped)  ox
```

**Expected behavior**
Control an empty buffer and do not panic.

**Screenshots**
![ox](https://user-images.githubusercontent.com/2903215/99050058-eb208b00-2597-11eb-89dc-f5c81166f8e2.gif)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - commit (fd24743)

**Comment by curlpipe** [comment]
duplicate
