### ISSUE TITLE
panicked at 'index out of bounds: the len is 6 but the index is 20', src/editor.rs:193:76

### ISSUE THREAD

**Issue by jdelgadoalfonso** [curlpipe/ox#79]
**Describe the bug**
Edit a file causes a panic when user pushes backspace key twice.

**To Reproduce**
1. Execute ox giving a file path as a parameter.
2. Press backspace key twice.
3. The application panics showing
```
thread 'main' panicked at 'index out of bounds: the len is 6 but the index is 20', src/editor.rs:193:76
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    842743 abort (core dumped)  ox README.md
```

**Expected behavior**
It should not try to erase when cursor is positioned in first character of the first line.

**Screenshots**
![ox](https://user-images.githubusercontent.com/2903215/99056536-b6fa9980-259a-11eb-958e-73d82dc7466f.gif)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - commit: (fd24743)

**Comment by curlpipe** [comment]
I believe this is a bug I've already fixed in 0.2.7 which is still being developed.
