### ISSUE TITLE
Double backspace provide error

### ISSUE THREAD

**Issue by joaoeudes7** [curlpipe/ox#82]
**Describe the bug**
Double backspace provide error `panicked at 'index out of bounds: the len is 0 but the index is 0', src/document.rs:385:21`

**To Reproduce**
1. Open Ox
2. Double Click in Backspace

**Expected behavior**
Nothing

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by curlpipe** [comment]
Already fixed in 0.2.7 which will be released soon.
