### ISSUE TITLE
Unable to open files with windows newline (\r\n)

### ISSUE THREAD

**Issue by vojta7** [curlpipe/ox#88]
**Describe the bug**
Ox freezes when on start when trying to open files with windows newlines and uses 100% of single CPU core. Nothing is rendered to the screen.

**To Reproduce**
1. Start ox with a file with windows newlines as the only argument: `ox file.txt`

**Expected behavior**
I expect ox to open the file with windows newlines and give me some visual hint that there are unprintable characters/windows newlines.

**Aditional info**
It seems that ox is stuck inside this [loop](https://github.com/curlpipe/ox/blob/79a8072ec5903e5d1255c5d47219aad7e9c2d98b/src/row.rs#L99), ch is '\r' so UnicodeWidthStr::width(*ch) returns 0, so there is nothing to break or advance this loop.

**Desktop (please complete the following information):**
 - OS: Arch Linux (x86_64)

**Comment by curlpipe** [comment]
I've already added support for this in 0.2.7 which is taking longer than I expected to produce.

**Comment by vojta7** [comment]
Sorry, I missed the 0.2.7 branch. And thank you for this software :+1:
