### ISSUE TITLE
Crash after double Ctrl+K in empty file

### ISSUE THREAD

**Issue by piotao** [curlpipe/ox#89]
**Describe the bug**
First of all, thank you for writing in Rust :) I like this language, but I'm still learning!
Solid crash occurs, when ox is run and open with no file, and when pressed Ctrl+K in empty buffer. Nothing typed. Crashed in alacritty as well as in konsole.  Seems to be solid and repeatable.

**To Reproduce**
1. In terminal, like alactitty (written in Rust too), or KDE konsole, run: RUST_BACKTRACE=full LC_ALL=C ox
2. Press twice Ctrl+K
3. Crash.
4. I collected the backtrace output in a file.

**Expected behavior**
No crash at all, maybe some other action, like some info in statusline, or whatever.

**Screenshots**
No screeshots

**Desktop (please complete the following information):**
 - OS: Linux
$ inxi
CPU: 6-Core Intel Core i7-9750H (-MT MCP-) speed/min/max: 800/800/4500 MHz Kernel: 5.3.0-64-generic x86_64 Up: 6d 23h 05m
Mem: 5128.7/31986.6 MiB (16.0%) Storage: 953.87 GiB (40.1% used) Procs: 284 Shell: bash 5.0.3 inxi: 3.0.36

$ inxi -SMGm
System:    Host: haran Kernel: 5.3.0-64-generic x86_64 bits: 64 Desktop: KDE Plasma 5.16.5 Distro: Ubuntu 19.10 (Eoan Ermine)
Machine:   Type: Laptop System: ASUSTeK product: ZenBook Pro Duo UX581GV_UX581GV v: 1.0 serial: <root required>
Mobo: ASUSTeK model: UX581GV v: 1.0 serial: <root required> UEFI: American Megatrends v: UX581GV.300
date: 08/29/2019
Memory:    RAM: total: 31.24 GiB used: 5.00 GiB (16.0%)
RAM Report: permissions: Unable to run dmidecode. Root privileges required.
Graphics:  Device-1: Intel UHD Graphics 630 driver: i915 v: kernel
Device-2: NVIDIA TU106M [GeForce RTX 2060 Mobile] driver: nvidia v: 435.21
Display: x11 server: X.Org 1.20.5 driver: modesetting,nvidia unloaded: fbdev,nouveau,vesa
resolution: 3840x2160~60Hz, 3840x1100~60Hz
OpenGL: renderer: GeForce RTX 2060/PCIe/SSE2 v: 4.6.0 NVIDIA 435.21

Please find attached a log from BACKTRACE=full.
[crash.txt](https://github.com/curlpipe/ox/files/5562986/crash.txt)

**Comment by piotao** [comment]
I forgot to add this - ox was installed just a minute ago, with command cargo install --git https://github.com/curlpipe/ox and after couple of seconds everything was done, no warnings. OX is working, but I don't know much how to use it (I'm a vim hardcore user). No modes - now way how to interact, really :)

**Comment by curlpipe** [comment]
I've written a (hopefully) comprehensive wiki that can be found at:
https://github.com/curlpipe/ox/wiki

I know the frustration of having a library or a program that has no good documentation, I see it way too often.

As for the bug, that has already been patched in 0.2.7, which is still a work in progress and taking a little longer than I predicted.

**Comment by piotao** [comment]
Thank you for the report and for nearly instant closing :) I didn't know about the patch and anything at all about ox. I have seen it just a few hours ago, by an accident, and I decided to give it a try. Nice idea. I'll look at the docs then. Good luck with this project! :)

**Comment by curlpipe** [comment]
Many thanks :D
