### ISSUE TITLE
Unable run on windows

### ISSUE THREAD

**Issue by bvj** [curlpipe/ox#90]
**Describe the bug**
Getting:
panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: Message("missing field `wrap_cursor`"), position: Position { line: 0, col: 0 } }', src\config.rs:71:32
when trying to start

**Expected behavior**
running editor

**Desktop (please complete the following information):**
 - OS: Windows 10]

**Comment by curlpipe** [comment]
If I am not mistaken, you are trying to run 0.2.7
This version is still not ready for use yet and I suggest using 0.2.6 in the meanwhile.
Have a good day.
