### ISSUE TITLE
Use backslash at beginning of a file cause crash

### ISSUE THREAD

**Issue by Busyvar** [curlpipe/ox#91]
In debug output it seems to be an issue there : src/editor.rs:186:35
If we take a look at comment on code it seems cursor position expectation was wrong
`// Backspace in the middle of a line
let row = self.doc[self.tab].rows[current.y].clone();
`
I don't see any detection of a backspace at the start of file, this case should be taken into account.

**Comment by curlpipe** [comment]
Already fixed in 0.2.7 which is still a work in progress but it's almost there.
