### ISSUE TITLE
Line duplicated on Ctrl-Up/Down

### ISSUE THREAD

**Issue by vlisivka** [curlpipe/ox#93]
**Describe the bug**
If a file contains one line, and Ctrl-Up or Ctrl-Down is pressed, the line is duplicated.

**To Reproduce**
1. Create new file.
2. Enter one line, without pressing of Enter key.
3. Press Ctrl-Up.

**Expected behavior**
Editor must do nothing, because the line cannot be moved.

**Actual behavior**
The line is duplicated.

**Screenshots**
Before:
![Screenshot_2020-11-22_21:27:05](https://user-images.githubusercontent.com/4396623/99914976-8a1c5400-2d09-11eb-9149-d1998a53e807.png)

After pressing of Ctrl-Up:
![Screenshot_2020-11-22_21:27:15](https://user-images.githubusercontent.com/4396623/99914975-8983bd80-2d09-11eb-9122-2b61bec05baf.png)

**Desktop (please complete the following information):**
 - OS: Fedora Linux

**Comment by curlpipe** [comment]
thanks for the report.

**Comment by tengkuizdihar** [comment]
This problem might be caused by the config/ox.ron.  Right now, CTRL+UP and CTRL+DOWN is binded to "move line up" and "move line down" respectively. I suspect that there's something wrong with the macro itself.

**Comment by tengkuizdihar** [comment]
I'm new to this project, but I suspect the macro is using the instruction inside of `interpret_line(...)` in `oxa.rs` right? I think the problem can be solved by fixing the behavior of `Event::InsertLineBelow` and `Event::InsertLineAbove` in the match scope inside of `execute(...)` in `document.rs`.

Correct me if I'm wrong, I consider myself a noob at this.

**Comment by curlpipe** [comment]
This was fixed (ox has been rewritten since, and it uses a completely different approach and there is no line duplication)
