### ISSUE TITLE
Syntax highlighting doesn't seem to be working

### ISSUE THREAD

**Issue by FearlessCaptain** [curlpipe/ox#94]
Hello! Syntax highlighting doesn't seem to be working. The screen shot attached shows latest Ox running on Latest Arch KDE with the Ox demo.rs file open. I've tested a number of files and none seems to be working. However I suspect this is user error on my part. Any suggestions on enabling highlighting?
![Screenshot_20201122_153059](https://user-images.githubusercontent.com/9869861/99916409-1dd52c80-2cd8-11eb-8948-c6743b681f39.png)

**Comment by curlpipe** [comment]
Are you using 0.2.7?

what does `ox -V` say?

**Comment by FearlessCaptain** [comment]
You've found the issue!

The version installed from Aur is 0.2.3. Building from source has fixed my issue. I suspect this is an issue with my Arch install/something cached as the Aur page for ox-bin shows 0.2.6.
