### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by KsRyY** [curlpipe/ox#95]
**Is your feature request related to a problem? Please describe.**
Ox will not compile on Windows, probably because termion does not support Windows.

**Describe the solution you'd like**
If possible, a small refactor that replaces termion by crossterm could solve the problem, if there is no path resolution problem (or Windows-specific action handling) in ox itself. There's also a crate called [crosstermion](https://github.com/Byron/prodash/tree/master/crosstermion) that can help migration.

**Describe alternatives you've considered**
I could not find any other TUI backend other than crossterm that supports Windows. Termion has a merge request for Windows support, but the project itself and that merge request had been inactive for a long time.

**Comment by curlpipe** [comment]
0.2.7 is written in crossterm and has full windows support.

**Comment by Tizoner** [comment]
App compiles but can't even find a provided path:
https://github.com/curlpipe/ox/issues/98

**Comment by qwerty01** [comment]
As noted above, it seems to have regressed and no longer works on windows, PR #113 fixes it though, the `log` macro was using a hardcoded temp path and the PR uses a package for generic temp files
