### ISSUE TITLE
Path completions/suggestions when opening files

### ISSUE THREAD

**Issue by detly** [curlpipe/ox#96]
When I use <kbd>ctrl</kbd>+<kbd>o</kbd> to open a file, it would be nice if as I type in a path, I could somehow see what existing paths are available for me to open. For me personally, the most expected way would be with <kbd>tab</kbd> (like Bash completion), where repeated <kbd>tab</kbd>s cycle through some options for completion. Other methods I've seen used:

- show all the next path "components" that match eg. `Do`<kbd>tab</kbd> shows `Downloads` and `Documents` in a space below, I can then type the full name that I want or the next letter and hit <kbd>tab</kbd> again to complete.
- show a dialog/overlay with a list of possibilities that I can use the arrow keys (or maybe typing as well) to select.

**Comment by curlpipe** [comment]
Good idea, I'll look into it

**Comment by curlpipe** [comment]
I've added something similar to how zsh autocomplete does it, where you'll see a dark grey part of the path past the cursor, which is the suggestion based on what you have already typed (see image below)

![image](https://github.com/user-attachments/assets/dacf3c78-6eb1-4c43-911c-d5273ad33dde)

The suggestion will change as you type

However, I haven't added something to cycle through different paths - but I'll look to add that in the next version

**Comment by curlpipe** [comment]
Fully implemented in 0.6.6

You can now use the `Tab` key to move forward to the next file / folder when it suggests one and `Shift + Tab` to move back to the previous suggestion.
