### ISSUE TITLE
Default theme

### ISSUE THREAD

**Issue by duboiss** [curlpipe/ox#97]
After an update to 0.2.7 (previously 0.2.5), I realized that the default theme is not the same anymore.
![image](https://user-images.githubusercontent.com/29716703/100133863-9cbc9780-2e87-11eb-9f18-d2257721b8b5.png)
A black background old school, is this normal?

I know we can configure the theme but doesn't the user expect to have the purple/green theme as presented in README.md ?
Having the purple/green theme as default values (as before) is a problem?

If you don't want it for one reason or another, why not have the background in the same color as the terminal? As nano does, so does mcedit.

**Comment by curlpipe** [comment]
yes I added a fallback theme on terminals that don't support full 24bit colours, just to make it not look weird on the tty. You can disable this by setting `fallback` in the theme section to `false`. Just out of curiosity, what terminal are you using?

**Comment by DuboisS** [comment]
Windows Terminal so i am surprised.
