### ISSUE TITLE
[Windows] The system cannot find the path specified.

### ISSUE THREAD

**Issue by Techassi** [curlpipe/ox#98]
**Describe the bug**
On Windows Im unable to use/open ox with the following error `The system cannot find the path specified.`

**To Reproduce**
1. Try to execute `ox`

**Expected behavior**
Ox opens.

**Stack Trace**

```shell
thread 'main' panicked at 'Err(Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." })', src\main.rs:65:5
stack backtrace:
   0:     0x7ff79fedb82d - <unknown>
   1:     0x7ff79fe564bb - <unknown>
   2:     0x7ff79feda571 - <unknown>
   3:     0x7ff79fed9cec - <unknown>
   4:     0x7ff79fee0daa - <unknown>
   5:     0x7ff79fee0d77 - <unknown>
   6:     0x7ff79fee0d1f - <unknown>
   7:     0x7ff79fee0ce0 - <unknown>
   8:     0x7ff79fdf5875 - <unknown>
   9:     0x7ff79fda38f6 - <unknown>
  10:     0x7ff79fe01a96 - <unknown>
  11:     0x7ff79fef6824 - <unknown>
  12:     0x7ffa94027034 - BaseThreadInitThunk
  13:     0x7ffa949fcec1 - RtlUserThreadStart
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Ox version: 0.2.7

It seems like `ox` is trying to open `/tmp/ox.log` which sadly doesn't exist on Windows. Maybe you should use the system-wide temporary directory (maybe via `std::env::temp_dir`). Note: Im not a Rust developer, I just did some quick googling

**Comment by Techassi** [comment]
Any update on this?

**Comment by curlpipe** [comment]
yes, apologies for the late response, I've been rewriting ox recently and this problem is no longer present, I've been very busy recently but it is going well.

**Comment by Techassi** [comment]
Okay great to hear. I'm curious to check out the new version!

**Comment by curlpipe** [comment]
Rewrite complete (it took a while :sweat_smile:)

This should be fixed, hopefully.
